### ISSUE TITLE
Make the multiplayer server 

### ISSUE THREAD

**Issue by erik90mx** [KOBUGE-Games/ringed#30] opened 2015-06-20 07:35 UTC
After a death match between @bojidar-bg  and @est31 

We decide that @est31 will make the server based in this class (Reines game)
https://github.com/KOBUGE-Games/reines/blob/master/server.gd

may the multiplayer games begin!

**Comment by mamarilmanson** [comment] 2015-06-20 07:40
:+1:

**Comment by bojidar-bg** [comment] 2015-07-14 07:28
#19 needs to get resolved first.

**Comment by est31** [comment] 2015-07-14 07:40
Dupe of #11

**Closed as completed by est31** 2015-07-14 07:40 UTC
Labels: Duplicate
